// Generated by CoffeeScript 1.3.1
(function() {

  window.ClientDetect = {
    scrollbarMetrics: function() {
      var div$, result;
      div$ = $('<div>').css({
        width: '1000px',
        height: '1000px',
        overflow: 'scroll',
        position: 'absolute',
        left: '-2000px',
        top: '-2000px'
      });
      $('body').append(div$);
      result = {
        width: div$.width() - div$[0].clientWidth,
        height: div$.height() - div$[0].clientHeight
      };
      div$.remove();
      return result;
    }
  };

}).call(this);
