// Generated by CoffeeScript 1.3.1
(function() {
  var DISABLE_TRANSITION,
    __slice = [].slice;

  window.ClientDetect = {
    scrollbarMetrics: function() {
      var div$, result;
      div$ = $('<div>').css({
        width: '1000px',
        height: '1000px',
        overflow: 'scroll',
        position: 'absolute',
        left: '-2000px',
        top: '-2000px'
      });
      $('body').append(div$);
      result = {
        width: div$.width() - div$[0].clientWidth,
        height: div$.height() - div$[0].clientHeight
      };
      div$.remove();
      return result;
    }
  };

  DISABLE_TRANSITION = "-webkit-transition: none !important;\n-moz-transition:    none !important;\n-o-transition       none !important;\n-ms-transition      none !important;\ntransition:         none !important;";

  Zepto.fn.cssNoTrans = function() {
    var args, finalStyle,
      _this = this;
    args = 1 <= arguments.length ? __slice.call(arguments, 0) : [];
    this.css.apply(this, args);
    finalStyle = this.attr('style');
    this.attr('style', "" + finalStyle + "; " + DISABLE_TRANSITION);
    return setTimeout((function() {
      return _this.attr('style', finalStyle);
    }), 0);
  };

}).call(this);
