// Generated by CoffeeScript 1.3.1
(function() {

  $(function() {
    var scrollbar_metrics;
    scrollbar_metrics = ClientDetect.scrollbarMetrics();
    return $('nav > *').cssNoTrans({
      right: scrollbar_metrics.width
    });
  });

}).call(this);
