// Generated by CoffeeScript 1.3.1
(function() {
  var DISABLE_TRANSITION,
    __slice = [].slice;

  $(function() {
    var scrollbar_metrics;
    scrollbar_metrics = ClientDetect.scrollbarMetrics();
    $('nav > *').cssNoTrans({
      right: scrollbar_metrics.width
    });
    return $('document, nav sections > *').scrollFix();
  });

  DISABLE_TRANSITION = "-webkit-transition: none !important;\n-moz-transition:    none !important;\n-o-transition       none !important;\n-ms-transition      none !important;\ntransition:         none !important;";

  Zepto.fn.cssNoTrans = function() {
    var args, finalStyle,
      _this = this;
    args = 1 <= arguments.length ? __slice.call(arguments, 0) : [];
    this.css.apply(this, args);
    finalStyle = this.attr('style');
    if (finalStyle instanceof CSSStyleDeclaration) {
      finalStyle = '';
    }
    this.attr('style', "" + finalStyle + "; " + DISABLE_TRANSITION);
    return setTimeout((function() {
      return _this.attr('style', finalStyle);
    }), 50);
  };

  Zepto.fn.scrollFix = function() {
    return this.each(function(i, node) {
      var node$;
      node$ = $(node);
      return node$.on('touchstart', function(evt) {
        if (node.scrollTop <= 0) {
          node.scrollTop = 1;
        }
        if (node.scrollTop + node.offsetHeight >= node.scrollHeight) {
          return node.scrollTop = node.scrollHeight - node.offsetHeight - 1;
        }
      });
    });
  };

}).call(this);
