// Generated by CoffeeScript 1.3.1
(function() {

  $(function() {
    var html$, sections$;
    html$ = $('html');
    sections$ = $('nav sections');
    return $('nav menu action').on('click', function(evt) {
      var section, target_section, _i, _len, _ref;
      if (!(target_section = $(evt.target).data('target-section'))) {
        return;
      }
      if (html$.hasClass('nav-expanded') && sections$.hasClass("" + target_section + "-active")) {
        return html$.removeClass('nav-expanded');
      }
      if (!html$.hasClass('nav-expanded')) {
        sections$.children().cssNoTrans();
        html$.addClass('nav-expanded');
      }
      _ref = sections$.children().map(function(i, n) {
        return n.nodeName.toLowerCase();
      });
      for (_i = 0, _len = _ref.length; _i < _len; _i++) {
        section = _ref[_i];
        sections$.removeClass("" + section + "-active");
      }
      return sections$.addClass("" + target_section + "-active");
    });
  });

}).call(this);
