// Generated by CoffeeScript 1.3.1
(function() {

  $(function() {
    return $('nav menu').on('click', function(evt) {
      return $('html').toggleClass('nav-expanded');
    });
  });

}).call(this);
